inhibit_all_warnings!

ios_version = '8.4'
osx_version = '10.7'

def library_pods
	podspec :path => '../MFDynamic.podspec'
end

def test_pods
  pod 'Kiwi', '~> 2.4'
end

# Library / Framework Targets

target "MFDynamic.iOS" do
	platform :ios, ios_version
	library_pods
end

target "MFDynamic.Mac" do
	platform :osx, osx_version
	library_pods
end

# Test Targets

target "MFDynamic.iOS.Tests" do
	platform :ios, ios_version
  library_pods
	test_pods
end

target "MFDynamic.Mac.Tests" do
	platform :osx, osx_version
	test_pods
end
